/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: api+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// PaginatedOrganizationCollection Paginated result
type PaginatedOrganizationCollection struct {
	Links        *PaginatedLinks                 `json:"_links,omitempty"`
	TotalItems   *int32                          `json:"totalItems,omitempty"`
	ItemsPerPage *int32                          `json:"itemsPerPage,omitempty"`
	Embedded     *EmbeddedOrganizationCollection `json:"_embedded,omitempty"`
}

// NewPaginatedOrganizationCollection instantiates a new PaginatedOrganizationCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedOrganizationCollection() *PaginatedOrganizationCollection {
	this := PaginatedOrganizationCollection{}
	return &this
}

// NewPaginatedOrganizationCollectionWithDefaults instantiates a new PaginatedOrganizationCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedOrganizationCollectionWithDefaults() *PaginatedOrganizationCollection {
	this := PaginatedOrganizationCollection{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *PaginatedOrganizationCollection) GetLinks() PaginatedLinks {
	if o == nil || o.Links == nil {
		var ret PaginatedLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedOrganizationCollection) GetLinksOk() (*PaginatedLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *PaginatedOrganizationCollection) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given PaginatedLinks and assigns it to the Links field.
func (o *PaginatedOrganizationCollection) SetLinks(v PaginatedLinks) {
	o.Links = &v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise.
func (o *PaginatedOrganizationCollection) GetTotalItems() int32 {
	if o == nil || o.TotalItems == nil {
		var ret int32
		return ret
	}
	return *o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedOrganizationCollection) GetTotalItemsOk() (*int32, bool) {
	if o == nil || o.TotalItems == nil {
		return nil, false
	}
	return o.TotalItems, true
}

// HasTotalItems returns a boolean if a field has been set.
func (o *PaginatedOrganizationCollection) HasTotalItems() bool {
	if o != nil && o.TotalItems != nil {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given int32 and assigns it to the TotalItems field.
func (o *PaginatedOrganizationCollection) SetTotalItems(v int32) {
	o.TotalItems = &v
}

// GetItemsPerPage returns the ItemsPerPage field value if set, zero value otherwise.
func (o *PaginatedOrganizationCollection) GetItemsPerPage() int32 {
	if o == nil || o.ItemsPerPage == nil {
		var ret int32
		return ret
	}
	return *o.ItemsPerPage
}

// GetItemsPerPageOk returns a tuple with the ItemsPerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedOrganizationCollection) GetItemsPerPageOk() (*int32, bool) {
	if o == nil || o.ItemsPerPage == nil {
		return nil, false
	}
	return o.ItemsPerPage, true
}

// HasItemsPerPage returns a boolean if a field has been set.
func (o *PaginatedOrganizationCollection) HasItemsPerPage() bool {
	if o != nil && o.ItemsPerPage != nil {
		return true
	}

	return false
}

// SetItemsPerPage gets a reference to the given int32 and assigns it to the ItemsPerPage field.
func (o *PaginatedOrganizationCollection) SetItemsPerPage(v int32) {
	o.ItemsPerPage = &v
}

// GetEmbedded returns the Embedded field value if set, zero value otherwise.
func (o *PaginatedOrganizationCollection) GetEmbedded() EmbeddedOrganizationCollection {
	if o == nil || o.Embedded == nil {
		var ret EmbeddedOrganizationCollection
		return ret
	}
	return *o.Embedded
}

// GetEmbeddedOk returns a tuple with the Embedded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedOrganizationCollection) GetEmbeddedOk() (*EmbeddedOrganizationCollection, bool) {
	if o == nil || o.Embedded == nil {
		return nil, false
	}
	return o.Embedded, true
}

// HasEmbedded returns a boolean if a field has been set.
func (o *PaginatedOrganizationCollection) HasEmbedded() bool {
	if o != nil && o.Embedded != nil {
		return true
	}

	return false
}

// SetEmbedded gets a reference to the given EmbeddedOrganizationCollection and assigns it to the Embedded field.
func (o *PaginatedOrganizationCollection) SetEmbedded(v EmbeddedOrganizationCollection) {
	o.Embedded = &v
}

func (o PaginatedOrganizationCollection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	if o.TotalItems != nil {
		toSerialize["totalItems"] = o.TotalItems
	}
	if o.ItemsPerPage != nil {
		toSerialize["itemsPerPage"] = o.ItemsPerPage
	}
	if o.Embedded != nil {
		toSerialize["_embedded"] = o.Embedded
	}
	return json.Marshal(toSerialize)
}

type NullablePaginatedOrganizationCollection struct {
	value *PaginatedOrganizationCollection
	isSet bool
}

func (v NullablePaginatedOrganizationCollection) Get() *PaginatedOrganizationCollection {
	return v.value
}

func (v *NullablePaginatedOrganizationCollection) Set(val *PaginatedOrganizationCollection) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedOrganizationCollection) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedOrganizationCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedOrganizationCollection(val *PaginatedOrganizationCollection) *NullablePaginatedOrganizationCollection {
	return &NullablePaginatedOrganizationCollection{value: val, isSet: true}
}

func (v NullablePaginatedOrganizationCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedOrganizationCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
