/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.0.1
Contact: api+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// OrganizationCollection An organization holds multiple projects and all the integrations used by environments
type OrganizationCollection struct {
	// Organization identifier.
	Id *string `json:"id,omitempty"`
	// Organization name as defined in Bunnyshell UI.
	Name *string `json:"name,omitempty"`
	// Organization timezone as defined in Bunnyshell UI.
	Timezone *string `json:"timezone,omitempty"`
}

// NewOrganizationCollection instantiates a new OrganizationCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationCollection() *OrganizationCollection {
	this := OrganizationCollection{}
	return &this
}

// NewOrganizationCollectionWithDefaults instantiates a new OrganizationCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationCollectionWithDefaults() *OrganizationCollection {
	this := OrganizationCollection{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrganizationCollection) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationCollection) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrganizationCollection) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OrganizationCollection) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrganizationCollection) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationCollection) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrganizationCollection) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrganizationCollection) SetName(v string) {
	o.Name = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *OrganizationCollection) GetTimezone() string {
	if o == nil || o.Timezone == nil {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationCollection) GetTimezoneOk() (*string, bool) {
	if o == nil || o.Timezone == nil {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *OrganizationCollection) HasTimezone() bool {
	if o != nil && o.Timezone != nil {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *OrganizationCollection) SetTimezone(v string) {
	o.Timezone = &v
}

func (o OrganizationCollection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Timezone != nil {
		toSerialize["timezone"] = o.Timezone
	}
	return json.Marshal(toSerialize)
}

type NullableOrganizationCollection struct {
	value *OrganizationCollection
	isSet bool
}

func (v NullableOrganizationCollection) Get() *OrganizationCollection {
	return v.value
}

func (v *NullableOrganizationCollection) Set(val *OrganizationCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationCollection(val *OrganizationCollection) *NullableOrganizationCollection {
	return &NullableOrganizationCollection{value: val, isSet: true}
}

func (v NullableOrganizationCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
