/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the EmbeddedServiceComponentVariableCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbeddedServiceComponentVariableCollection{}

// EmbeddedServiceComponentVariableCollection struct for EmbeddedServiceComponentVariableCollection
type EmbeddedServiceComponentVariableCollection struct {
	Item []ServiceComponentVariableCollection `json:"item,omitempty"`
}

// NewEmbeddedServiceComponentVariableCollection instantiates a new EmbeddedServiceComponentVariableCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedServiceComponentVariableCollection() *EmbeddedServiceComponentVariableCollection {
	this := EmbeddedServiceComponentVariableCollection{}
	return &this
}

// NewEmbeddedServiceComponentVariableCollectionWithDefaults instantiates a new EmbeddedServiceComponentVariableCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedServiceComponentVariableCollectionWithDefaults() *EmbeddedServiceComponentVariableCollection {
	this := EmbeddedServiceComponentVariableCollection{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *EmbeddedServiceComponentVariableCollection) GetItem() []ServiceComponentVariableCollection {
	if o == nil || IsNil(o.Item) {
		var ret []ServiceComponentVariableCollection
		return ret
	}
	return o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedServiceComponentVariableCollection) GetItemOk() ([]ServiceComponentVariableCollection, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *EmbeddedServiceComponentVariableCollection) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given []ServiceComponentVariableCollection and assigns it to the Item field.
func (o *EmbeddedServiceComponentVariableCollection) SetItem(v []ServiceComponentVariableCollection) {
	o.Item = v
}

func (o EmbeddedServiceComponentVariableCollection) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbeddedServiceComponentVariableCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableEmbeddedServiceComponentVariableCollection struct {
	value *EmbeddedServiceComponentVariableCollection
	isSet bool
}

func (v NullableEmbeddedServiceComponentVariableCollection) Get() *EmbeddedServiceComponentVariableCollection {
	return v.value
}

func (v *NullableEmbeddedServiceComponentVariableCollection) Set(val *EmbeddedServiceComponentVariableCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedServiceComponentVariableCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedServiceComponentVariableCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedServiceComponentVariableCollection(val *EmbeddedServiceComponentVariableCollection) *NullableEmbeddedServiceComponentVariableCollection {
	return &NullableEmbeddedServiceComponentVariableCollection{value: val, isSet: true}
}

func (v NullableEmbeddedServiceComponentVariableCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedServiceComponentVariableCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
