/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the EmbeddedTemplatesRepositoryCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbeddedTemplatesRepositoryCollection{}

// EmbeddedTemplatesRepositoryCollection struct for EmbeddedTemplatesRepositoryCollection
type EmbeddedTemplatesRepositoryCollection struct {
	Item []TemplatesRepositoryCollection `json:"item,omitempty"`
}

// NewEmbeddedTemplatesRepositoryCollection instantiates a new EmbeddedTemplatesRepositoryCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedTemplatesRepositoryCollection() *EmbeddedTemplatesRepositoryCollection {
	this := EmbeddedTemplatesRepositoryCollection{}
	return &this
}

// NewEmbeddedTemplatesRepositoryCollectionWithDefaults instantiates a new EmbeddedTemplatesRepositoryCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedTemplatesRepositoryCollectionWithDefaults() *EmbeddedTemplatesRepositoryCollection {
	this := EmbeddedTemplatesRepositoryCollection{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *EmbeddedTemplatesRepositoryCollection) GetItem() []TemplatesRepositoryCollection {
	if o == nil || IsNil(o.Item) {
		var ret []TemplatesRepositoryCollection
		return ret
	}
	return o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedTemplatesRepositoryCollection) GetItemOk() ([]TemplatesRepositoryCollection, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *EmbeddedTemplatesRepositoryCollection) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given []TemplatesRepositoryCollection and assigns it to the Item field.
func (o *EmbeddedTemplatesRepositoryCollection) SetItem(v []TemplatesRepositoryCollection) {
	o.Item = v
}

func (o EmbeddedTemplatesRepositoryCollection) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbeddedTemplatesRepositoryCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableEmbeddedTemplatesRepositoryCollection struct {
	value *EmbeddedTemplatesRepositoryCollection
	isSet bool
}

func (v NullableEmbeddedTemplatesRepositoryCollection) Get() *EmbeddedTemplatesRepositoryCollection {
	return v.value
}

func (v *NullableEmbeddedTemplatesRepositoryCollection) Set(val *EmbeddedTemplatesRepositoryCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedTemplatesRepositoryCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedTemplatesRepositoryCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedTemplatesRepositoryCollection(val *EmbeddedTemplatesRepositoryCollection) *NullableEmbeddedTemplatesRepositoryCollection {
	return &NullableEmbeddedTemplatesRepositoryCollection{value: val, isSet: true}
}

func (v NullableEmbeddedTemplatesRepositoryCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedTemplatesRepositoryCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
