/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// EnvironmentEditActionGenesis - The environment update source
type EnvironmentEditActionGenesis struct {
	FromGit      *FromGit
	FromGitSpec  *FromGitSpec
	FromString   *FromString
	FromTemplate *FromTemplate
}

// FromGitAsEnvironmentEditActionGenesis is a convenience function that returns FromGit wrapped in EnvironmentEditActionGenesis
func FromGitAsEnvironmentEditActionGenesis(v *FromGit) EnvironmentEditActionGenesis {
	return EnvironmentEditActionGenesis{
		FromGit: v,
	}
}

// FromGitSpecAsEnvironmentEditActionGenesis is a convenience function that returns FromGitSpec wrapped in EnvironmentEditActionGenesis
func FromGitSpecAsEnvironmentEditActionGenesis(v *FromGitSpec) EnvironmentEditActionGenesis {
	return EnvironmentEditActionGenesis{
		FromGitSpec: v,
	}
}

// FromStringAsEnvironmentEditActionGenesis is a convenience function that returns FromString wrapped in EnvironmentEditActionGenesis
func FromStringAsEnvironmentEditActionGenesis(v *FromString) EnvironmentEditActionGenesis {
	return EnvironmentEditActionGenesis{
		FromString: v,
	}
}

// FromTemplateAsEnvironmentEditActionGenesis is a convenience function that returns FromTemplate wrapped in EnvironmentEditActionGenesis
func FromTemplateAsEnvironmentEditActionGenesis(v *FromTemplate) EnvironmentEditActionGenesis {
	return EnvironmentEditActionGenesis{
		FromTemplate: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *EnvironmentEditActionGenesis) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into FromGit
	err = newStrictDecoder(data).Decode(&dst.FromGit)
	if err == nil {
		jsonFromGit, _ := json.Marshal(dst.FromGit)
		if string(jsonFromGit) == "{}" { // empty struct
			dst.FromGit = nil
		} else {
			match++
		}
	} else {
		dst.FromGit = nil
	}

	// try to unmarshal data into FromGitSpec
	err = newStrictDecoder(data).Decode(&dst.FromGitSpec)
	if err == nil {
		jsonFromGitSpec, _ := json.Marshal(dst.FromGitSpec)
		if string(jsonFromGitSpec) == "{}" { // empty struct
			dst.FromGitSpec = nil
		} else {
			match++
		}
	} else {
		dst.FromGitSpec = nil
	}

	// try to unmarshal data into FromString
	err = newStrictDecoder(data).Decode(&dst.FromString)
	if err == nil {
		jsonFromString, _ := json.Marshal(dst.FromString)
		if string(jsonFromString) == "{}" { // empty struct
			dst.FromString = nil
		} else {
			match++
		}
	} else {
		dst.FromString = nil
	}

	// try to unmarshal data into FromTemplate
	err = newStrictDecoder(data).Decode(&dst.FromTemplate)
	if err == nil {
		jsonFromTemplate, _ := json.Marshal(dst.FromTemplate)
		if string(jsonFromTemplate) == "{}" { // empty struct
			dst.FromTemplate = nil
		} else {
			match++
		}
	} else {
		dst.FromTemplate = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.FromGit = nil
		dst.FromGitSpec = nil
		dst.FromString = nil
		dst.FromTemplate = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(EnvironmentEditActionGenesis)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(EnvironmentEditActionGenesis)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src EnvironmentEditActionGenesis) MarshalJSON() ([]byte, error) {
	if src.FromGit != nil {
		return json.Marshal(&src.FromGit)
	}

	if src.FromGitSpec != nil {
		return json.Marshal(&src.FromGitSpec)
	}

	if src.FromString != nil {
		return json.Marshal(&src.FromString)
	}

	if src.FromTemplate != nil {
		return json.Marshal(&src.FromTemplate)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *EnvironmentEditActionGenesis) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FromGit != nil {
		return obj.FromGit
	}

	if obj.FromGitSpec != nil {
		return obj.FromGitSpec
	}

	if obj.FromString != nil {
		return obj.FromString
	}

	if obj.FromTemplate != nil {
		return obj.FromTemplate
	}

	// all schemas are nil
	return nil
}

type NullableEnvironmentEditActionGenesis struct {
	value *EnvironmentEditActionGenesis
	isSet bool
}

func (v NullableEnvironmentEditActionGenesis) Get() *EnvironmentEditActionGenesis {
	return v.value
}

func (v *NullableEnvironmentEditActionGenesis) Set(val *EnvironmentEditActionGenesis) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentEditActionGenesis) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentEditActionGenesis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentEditActionGenesis(val *EnvironmentEditActionGenesis) *NullableEnvironmentEditActionGenesis {
	return &NullableEnvironmentEditActionGenesis{value: val, isSet: true}
}

func (v NullableEnvironmentEditActionGenesis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentEditActionGenesis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
