/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the TemplateSettingsEdit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateSettingsEdit{}

// TemplateSettingsEdit struct for TemplateSettingsEdit
type TemplateSettingsEdit struct {
	BranchFallbackOnDelete           NullableBool `json:"branchFallbackOnDelete,omitempty"`
	BranchFallbackOnDeleteAutoDeploy NullableBool `json:"branchFallbackOnDeleteAutoDeploy,omitempty"`
}

// NewTemplateSettingsEdit instantiates a new TemplateSettingsEdit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateSettingsEdit() *TemplateSettingsEdit {
	this := TemplateSettingsEdit{}
	return &this
}

// NewTemplateSettingsEditWithDefaults instantiates a new TemplateSettingsEdit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateSettingsEditWithDefaults() *TemplateSettingsEdit {
	this := TemplateSettingsEdit{}
	return &this
}

// GetBranchFallbackOnDelete returns the BranchFallbackOnDelete field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateSettingsEdit) GetBranchFallbackOnDelete() bool {
	if o == nil || IsNil(o.BranchFallbackOnDelete.Get()) {
		var ret bool
		return ret
	}
	return *o.BranchFallbackOnDelete.Get()
}

// GetBranchFallbackOnDeleteOk returns a tuple with the BranchFallbackOnDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateSettingsEdit) GetBranchFallbackOnDeleteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.BranchFallbackOnDelete.Get(), o.BranchFallbackOnDelete.IsSet()
}

// HasBranchFallbackOnDelete returns a boolean if a field has been set.
func (o *TemplateSettingsEdit) HasBranchFallbackOnDelete() bool {
	if o != nil && o.BranchFallbackOnDelete.IsSet() {
		return true
	}

	return false
}

// SetBranchFallbackOnDelete gets a reference to the given NullableBool and assigns it to the BranchFallbackOnDelete field.
func (o *TemplateSettingsEdit) SetBranchFallbackOnDelete(v bool) {
	o.BranchFallbackOnDelete.Set(&v)
}

// SetBranchFallbackOnDeleteNil sets the value for BranchFallbackOnDelete to be an explicit nil
func (o *TemplateSettingsEdit) SetBranchFallbackOnDeleteNil() {
	o.BranchFallbackOnDelete.Set(nil)
}

// UnsetBranchFallbackOnDelete ensures that no value is present for BranchFallbackOnDelete, not even an explicit nil
func (o *TemplateSettingsEdit) UnsetBranchFallbackOnDelete() {
	o.BranchFallbackOnDelete.Unset()
}

// GetBranchFallbackOnDeleteAutoDeploy returns the BranchFallbackOnDeleteAutoDeploy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateSettingsEdit) GetBranchFallbackOnDeleteAutoDeploy() bool {
	if o == nil || IsNil(o.BranchFallbackOnDeleteAutoDeploy.Get()) {
		var ret bool
		return ret
	}
	return *o.BranchFallbackOnDeleteAutoDeploy.Get()
}

// GetBranchFallbackOnDeleteAutoDeployOk returns a tuple with the BranchFallbackOnDeleteAutoDeploy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateSettingsEdit) GetBranchFallbackOnDeleteAutoDeployOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.BranchFallbackOnDeleteAutoDeploy.Get(), o.BranchFallbackOnDeleteAutoDeploy.IsSet()
}

// HasBranchFallbackOnDeleteAutoDeploy returns a boolean if a field has been set.
func (o *TemplateSettingsEdit) HasBranchFallbackOnDeleteAutoDeploy() bool {
	if o != nil && o.BranchFallbackOnDeleteAutoDeploy.IsSet() {
		return true
	}

	return false
}

// SetBranchFallbackOnDeleteAutoDeploy gets a reference to the given NullableBool and assigns it to the BranchFallbackOnDeleteAutoDeploy field.
func (o *TemplateSettingsEdit) SetBranchFallbackOnDeleteAutoDeploy(v bool) {
	o.BranchFallbackOnDeleteAutoDeploy.Set(&v)
}

// SetBranchFallbackOnDeleteAutoDeployNil sets the value for BranchFallbackOnDeleteAutoDeploy to be an explicit nil
func (o *TemplateSettingsEdit) SetBranchFallbackOnDeleteAutoDeployNil() {
	o.BranchFallbackOnDeleteAutoDeploy.Set(nil)
}

// UnsetBranchFallbackOnDeleteAutoDeploy ensures that no value is present for BranchFallbackOnDeleteAutoDeploy, not even an explicit nil
func (o *TemplateSettingsEdit) UnsetBranchFallbackOnDeleteAutoDeploy() {
	o.BranchFallbackOnDeleteAutoDeploy.Unset()
}

func (o TemplateSettingsEdit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateSettingsEdit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BranchFallbackOnDelete.IsSet() {
		toSerialize["branchFallbackOnDelete"] = o.BranchFallbackOnDelete.Get()
	}
	if o.BranchFallbackOnDeleteAutoDeploy.IsSet() {
		toSerialize["branchFallbackOnDeleteAutoDeploy"] = o.BranchFallbackOnDeleteAutoDeploy.Get()
	}
	return toSerialize, nil
}

type NullableTemplateSettingsEdit struct {
	value *TemplateSettingsEdit
	isSet bool
}

func (v NullableTemplateSettingsEdit) Get() *TemplateSettingsEdit {
	return v.value
}

func (v *NullableTemplateSettingsEdit) Set(val *TemplateSettingsEdit) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateSettingsEdit) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateSettingsEdit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateSettingsEdit(val *TemplateSettingsEdit) *NullableTemplateSettingsEdit {
	return &NullableTemplateSettingsEdit{value: val, isSet: true}
}

func (v NullableTemplateSettingsEdit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateSettingsEdit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
