/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// EmbeddedKubernetesIntegrationCollection struct for EmbeddedKubernetesIntegrationCollection
type EmbeddedKubernetesIntegrationCollection struct {
	Item []KubernetesIntegrationCollection `json:"item,omitempty"`
}

// NewEmbeddedKubernetesIntegrationCollection instantiates a new EmbeddedKubernetesIntegrationCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedKubernetesIntegrationCollection() *EmbeddedKubernetesIntegrationCollection {
	this := EmbeddedKubernetesIntegrationCollection{}
	return &this
}

// NewEmbeddedKubernetesIntegrationCollectionWithDefaults instantiates a new EmbeddedKubernetesIntegrationCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedKubernetesIntegrationCollectionWithDefaults() *EmbeddedKubernetesIntegrationCollection {
	this := EmbeddedKubernetesIntegrationCollection{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *EmbeddedKubernetesIntegrationCollection) GetItem() []KubernetesIntegrationCollection {
	if o == nil || o.Item == nil {
		var ret []KubernetesIntegrationCollection
		return ret
	}
	return o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedKubernetesIntegrationCollection) GetItemOk() ([]KubernetesIntegrationCollection, bool) {
	if o == nil || o.Item == nil {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *EmbeddedKubernetesIntegrationCollection) HasItem() bool {
	if o != nil && o.Item != nil {
		return true
	}

	return false
}

// SetItem gets a reference to the given []KubernetesIntegrationCollection and assigns it to the Item field.
func (o *EmbeddedKubernetesIntegrationCollection) SetItem(v []KubernetesIntegrationCollection) {
	o.Item = v
}

func (o EmbeddedKubernetesIntegrationCollection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Item != nil {
		toSerialize["item"] = o.Item
	}
	return json.Marshal(toSerialize)
}

type NullableEmbeddedKubernetesIntegrationCollection struct {
	value *EmbeddedKubernetesIntegrationCollection
	isSet bool
}

func (v NullableEmbeddedKubernetesIntegrationCollection) Get() *EmbeddedKubernetesIntegrationCollection {
	return v.value
}

func (v *NullableEmbeddedKubernetesIntegrationCollection) Set(val *EmbeddedKubernetesIntegrationCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedKubernetesIntegrationCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedKubernetesIntegrationCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedKubernetesIntegrationCollection(val *EmbeddedKubernetesIntegrationCollection) *NullableEmbeddedKubernetesIntegrationCollection {
	return &NullableEmbeddedKubernetesIntegrationCollection{value: val, isSet: true}
}

func (v NullableEmbeddedKubernetesIntegrationCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedKubernetesIntegrationCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
