/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UserWrapperKubeConfigRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserWrapperKubeConfigRead{}

// UserWrapperKubeConfigRead struct for UserWrapperKubeConfigRead
type UserWrapperKubeConfigRead struct {
	Name string             `json:"name"`
	User UserKubeConfigRead `json:"user"`
}

// NewUserWrapperKubeConfigRead instantiates a new UserWrapperKubeConfigRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserWrapperKubeConfigRead(name string, user UserKubeConfigRead) *UserWrapperKubeConfigRead {
	this := UserWrapperKubeConfigRead{}
	this.Name = name
	this.User = user
	return &this
}

// NewUserWrapperKubeConfigReadWithDefaults instantiates a new UserWrapperKubeConfigRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWrapperKubeConfigReadWithDefaults() *UserWrapperKubeConfigRead {
	this := UserWrapperKubeConfigRead{}
	return &this
}

// GetName returns the Name field value
func (o *UserWrapperKubeConfigRead) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserWrapperKubeConfigRead) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserWrapperKubeConfigRead) SetName(v string) {
	o.Name = v
}

// GetUser returns the User field value
func (o *UserWrapperKubeConfigRead) GetUser() UserKubeConfigRead {
	if o == nil {
		var ret UserKubeConfigRead
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *UserWrapperKubeConfigRead) GetUserOk() (*UserKubeConfigRead, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *UserWrapperKubeConfigRead) SetUser(v UserKubeConfigRead) {
	o.User = v
}

func (o UserWrapperKubeConfigRead) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserWrapperKubeConfigRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["user"] = o.User
	return toSerialize, nil
}

type NullableUserWrapperKubeConfigRead struct {
	value *UserWrapperKubeConfigRead
	isSet bool
}

func (v NullableUserWrapperKubeConfigRead) Get() *UserWrapperKubeConfigRead {
	return v.value
}

func (v *NullableUserWrapperKubeConfigRead) Set(val *UserWrapperKubeConfigRead) {
	v.value = val
	v.isSet = true
}

func (v NullableUserWrapperKubeConfigRead) IsSet() bool {
	return v.isSet
}

func (v *NullableUserWrapperKubeConfigRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserWrapperKubeConfigRead(val *UserWrapperKubeConfigRead) *NullableUserWrapperKubeConfigRead {
	return &NullableUserWrapperKubeConfigRead{value: val, isSet: true}
}

func (v NullableUserWrapperKubeConfigRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserWrapperKubeConfigRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
