/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the WorkflowJobWorkflowJobLogsOutputItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowJobWorkflowJobLogsOutputItem{}

// WorkflowJobWorkflowJobLogsOutputItem A workflow job.
type WorkflowJobWorkflowJobLogsOutputItem struct {
	WorkflowJob *WorkflowJobOutputItem `json:"workflowJob,omitempty"`
	// Workflow job steps and logs.
	Steps []WorkflowStepOutputItem `json:"steps,omitempty"`
}

// NewWorkflowJobWorkflowJobLogsOutputItem instantiates a new WorkflowJobWorkflowJobLogsOutputItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowJobWorkflowJobLogsOutputItem() *WorkflowJobWorkflowJobLogsOutputItem {
	this := WorkflowJobWorkflowJobLogsOutputItem{}
	return &this
}

// NewWorkflowJobWorkflowJobLogsOutputItemWithDefaults instantiates a new WorkflowJobWorkflowJobLogsOutputItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowJobWorkflowJobLogsOutputItemWithDefaults() *WorkflowJobWorkflowJobLogsOutputItem {
	this := WorkflowJobWorkflowJobLogsOutputItem{}
	return &this
}

// GetWorkflowJob returns the WorkflowJob field value if set, zero value otherwise.
func (o *WorkflowJobWorkflowJobLogsOutputItem) GetWorkflowJob() WorkflowJobOutputItem {
	if o == nil || IsNil(o.WorkflowJob) {
		var ret WorkflowJobOutputItem
		return ret
	}
	return *o.WorkflowJob
}

// GetWorkflowJobOk returns a tuple with the WorkflowJob field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowJobWorkflowJobLogsOutputItem) GetWorkflowJobOk() (*WorkflowJobOutputItem, bool) {
	if o == nil || IsNil(o.WorkflowJob) {
		return nil, false
	}
	return o.WorkflowJob, true
}

// HasWorkflowJob returns a boolean if a field has been set.
func (o *WorkflowJobWorkflowJobLogsOutputItem) HasWorkflowJob() bool {
	if o != nil && !IsNil(o.WorkflowJob) {
		return true
	}

	return false
}

// SetWorkflowJob gets a reference to the given WorkflowJobOutputItem and assigns it to the WorkflowJob field.
func (o *WorkflowJobWorkflowJobLogsOutputItem) SetWorkflowJob(v WorkflowJobOutputItem) {
	o.WorkflowJob = &v
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *WorkflowJobWorkflowJobLogsOutputItem) GetSteps() []WorkflowStepOutputItem {
	if o == nil || IsNil(o.Steps) {
		var ret []WorkflowStepOutputItem
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowJobWorkflowJobLogsOutputItem) GetStepsOk() ([]WorkflowStepOutputItem, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *WorkflowJobWorkflowJobLogsOutputItem) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []WorkflowStepOutputItem and assigns it to the Steps field.
func (o *WorkflowJobWorkflowJobLogsOutputItem) SetSteps(v []WorkflowStepOutputItem) {
	o.Steps = v
}

func (o WorkflowJobWorkflowJobLogsOutputItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowJobWorkflowJobLogsOutputItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WorkflowJob) {
		toSerialize["workflowJob"] = o.WorkflowJob
	}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	return toSerialize, nil
}

type NullableWorkflowJobWorkflowJobLogsOutputItem struct {
	value *WorkflowJobWorkflowJobLogsOutputItem
	isSet bool
}

func (v NullableWorkflowJobWorkflowJobLogsOutputItem) Get() *WorkflowJobWorkflowJobLogsOutputItem {
	return v.value
}

func (v *NullableWorkflowJobWorkflowJobLogsOutputItem) Set(val *WorkflowJobWorkflowJobLogsOutputItem) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowJobWorkflowJobLogsOutputItem) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowJobWorkflowJobLogsOutputItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowJobWorkflowJobLogsOutputItem(val *WorkflowJobWorkflowJobLogsOutputItem) *NullableWorkflowJobWorkflowJobLogsOutputItem {
	return &NullableWorkflowJobWorkflowJobLogsOutputItem{value: val, isSet: true}
}

func (v NullableWorkflowJobWorkflowJobLogsOutputItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowJobWorkflowJobLogsOutputItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
