/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the EnvironmentPartialStopAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentPartialStopAction{}

// EnvironmentPartialStopAction An environment holds a collection of buildable and deployable components.
type EnvironmentPartialStopAction struct {
	QueueIfSomethingInProgress *bool    `json:"queueIfSomethingInProgress,omitempty"`
	IsPartial                  *bool    `json:"isPartial,omitempty"`
	Components                 []string `json:"components,omitempty"`
}

// NewEnvironmentPartialStopAction instantiates a new EnvironmentPartialStopAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentPartialStopAction() *EnvironmentPartialStopAction {
	this := EnvironmentPartialStopAction{}
	return &this
}

// NewEnvironmentPartialStopActionWithDefaults instantiates a new EnvironmentPartialStopAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentPartialStopActionWithDefaults() *EnvironmentPartialStopAction {
	this := EnvironmentPartialStopAction{}
	return &this
}

// GetQueueIfSomethingInProgress returns the QueueIfSomethingInProgress field value if set, zero value otherwise.
func (o *EnvironmentPartialStopAction) GetQueueIfSomethingInProgress() bool {
	if o == nil || IsNil(o.QueueIfSomethingInProgress) {
		var ret bool
		return ret
	}
	return *o.QueueIfSomethingInProgress
}

// GetQueueIfSomethingInProgressOk returns a tuple with the QueueIfSomethingInProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentPartialStopAction) GetQueueIfSomethingInProgressOk() (*bool, bool) {
	if o == nil || IsNil(o.QueueIfSomethingInProgress) {
		return nil, false
	}
	return o.QueueIfSomethingInProgress, true
}

// HasQueueIfSomethingInProgress returns a boolean if a field has been set.
func (o *EnvironmentPartialStopAction) HasQueueIfSomethingInProgress() bool {
	if o != nil && !IsNil(o.QueueIfSomethingInProgress) {
		return true
	}

	return false
}

// SetQueueIfSomethingInProgress gets a reference to the given bool and assigns it to the QueueIfSomethingInProgress field.
func (o *EnvironmentPartialStopAction) SetQueueIfSomethingInProgress(v bool) {
	o.QueueIfSomethingInProgress = &v
}

// GetIsPartial returns the IsPartial field value if set, zero value otherwise.
func (o *EnvironmentPartialStopAction) GetIsPartial() bool {
	if o == nil || IsNil(o.IsPartial) {
		var ret bool
		return ret
	}
	return *o.IsPartial
}

// GetIsPartialOk returns a tuple with the IsPartial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentPartialStopAction) GetIsPartialOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPartial) {
		return nil, false
	}
	return o.IsPartial, true
}

// HasIsPartial returns a boolean if a field has been set.
func (o *EnvironmentPartialStopAction) HasIsPartial() bool {
	if o != nil && !IsNil(o.IsPartial) {
		return true
	}

	return false
}

// SetIsPartial gets a reference to the given bool and assigns it to the IsPartial field.
func (o *EnvironmentPartialStopAction) SetIsPartial(v bool) {
	o.IsPartial = &v
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *EnvironmentPartialStopAction) GetComponents() []string {
	if o == nil || IsNil(o.Components) {
		var ret []string
		return ret
	}
	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentPartialStopAction) GetComponentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *EnvironmentPartialStopAction) HasComponents() bool {
	if o != nil && !IsNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given []string and assigns it to the Components field.
func (o *EnvironmentPartialStopAction) SetComponents(v []string) {
	o.Components = v
}

func (o EnvironmentPartialStopAction) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentPartialStopAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.QueueIfSomethingInProgress) {
		toSerialize["queueIfSomethingInProgress"] = o.QueueIfSomethingInProgress
	}
	if !IsNil(o.IsPartial) {
		toSerialize["isPartial"] = o.IsPartial
	}
	if !IsNil(o.Components) {
		toSerialize["components"] = o.Components
	}
	return toSerialize, nil
}

type NullableEnvironmentPartialStopAction struct {
	value *EnvironmentPartialStopAction
	isSet bool
}

func (v NullableEnvironmentPartialStopAction) Get() *EnvironmentPartialStopAction {
	return v.value
}

func (v *NullableEnvironmentPartialStopAction) Set(val *EnvironmentPartialStopAction) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentPartialStopAction) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentPartialStopAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentPartialStopAction(val *EnvironmentPartialStopAction) *NullableEnvironmentPartialStopAction {
	return &NullableEnvironmentPartialStopAction{value: val, isSet: true}
}

func (v NullableEnvironmentPartialStopAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentPartialStopAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
