/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// EnvironmentCreateActionGenesis - The environment creation method
type EnvironmentCreateActionGenesis struct {
	FromGit      *FromGit
	FromGitSpec  *FromGitSpec
	FromString   *FromString
	FromTemplate *FromTemplate
}

// FromGitAsEnvironmentCreateActionGenesis is a convenience function that returns FromGit wrapped in EnvironmentCreateActionGenesis
func FromGitAsEnvironmentCreateActionGenesis(v *FromGit) EnvironmentCreateActionGenesis {
	return EnvironmentCreateActionGenesis{
		FromGit: v,
	}
}

// FromGitSpecAsEnvironmentCreateActionGenesis is a convenience function that returns FromGitSpec wrapped in EnvironmentCreateActionGenesis
func FromGitSpecAsEnvironmentCreateActionGenesis(v *FromGitSpec) EnvironmentCreateActionGenesis {
	return EnvironmentCreateActionGenesis{
		FromGitSpec: v,
	}
}

// FromStringAsEnvironmentCreateActionGenesis is a convenience function that returns FromString wrapped in EnvironmentCreateActionGenesis
func FromStringAsEnvironmentCreateActionGenesis(v *FromString) EnvironmentCreateActionGenesis {
	return EnvironmentCreateActionGenesis{
		FromString: v,
	}
}

// FromTemplateAsEnvironmentCreateActionGenesis is a convenience function that returns FromTemplate wrapped in EnvironmentCreateActionGenesis
func FromTemplateAsEnvironmentCreateActionGenesis(v *FromTemplate) EnvironmentCreateActionGenesis {
	return EnvironmentCreateActionGenesis{
		FromTemplate: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *EnvironmentCreateActionGenesis) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into FromGit
	err = json.Unmarshal(data, &dst.FromGit)
	if err == nil {
		jsonFromGit, _ := json.Marshal(dst.FromGit)
		if string(jsonFromGit) == "{}" { // empty struct
			dst.FromGit = nil
		} else {
			match++
		}
	} else {
		dst.FromGit = nil
	}

	// try to unmarshal data into FromGitSpec
	err = json.Unmarshal(data, &dst.FromGitSpec)
	if err == nil {
		jsonFromGitSpec, _ := json.Marshal(dst.FromGitSpec)
		if string(jsonFromGitSpec) == "{}" { // empty struct
			dst.FromGitSpec = nil
		} else {
			match++
		}
	} else {
		dst.FromGitSpec = nil
	}

	// try to unmarshal data into FromString
	err = json.Unmarshal(data, &dst.FromString)
	if err == nil {
		jsonFromString, _ := json.Marshal(dst.FromString)
		if string(jsonFromString) == "{}" { // empty struct
			dst.FromString = nil
		} else {
			match++
		}
	} else {
		dst.FromString = nil
	}

	// try to unmarshal data into FromTemplate
	err = json.Unmarshal(data, &dst.FromTemplate)
	if err == nil {
		jsonFromTemplate, _ := json.Marshal(dst.FromTemplate)
		if string(jsonFromTemplate) == "{}" { // empty struct
			dst.FromTemplate = nil
		} else {
			match++
		}
	} else {
		dst.FromTemplate = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.FromGit = nil
		dst.FromGitSpec = nil
		dst.FromString = nil
		dst.FromTemplate = nil

		return fmt.Errorf("data matches more than one schema in oneOf(EnvironmentCreateActionGenesis)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(EnvironmentCreateActionGenesis)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src EnvironmentCreateActionGenesis) MarshalJSON() ([]byte, error) {
	if src.FromGit != nil {
		return json.Marshal(&src.FromGit)
	}

	if src.FromGitSpec != nil {
		return json.Marshal(&src.FromGitSpec)
	}

	if src.FromString != nil {
		return json.Marshal(&src.FromString)
	}

	if src.FromTemplate != nil {
		return json.Marshal(&src.FromTemplate)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *EnvironmentCreateActionGenesis) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FromGit != nil {
		return obj.FromGit
	}

	if obj.FromGitSpec != nil {
		return obj.FromGitSpec
	}

	if obj.FromString != nil {
		return obj.FromString
	}

	if obj.FromTemplate != nil {
		return obj.FromTemplate
	}

	// all schemas are nil
	return nil
}

type NullableEnvironmentCreateActionGenesis struct {
	value *EnvironmentCreateActionGenesis
	isSet bool
}

func (v NullableEnvironmentCreateActionGenesis) Get() *EnvironmentCreateActionGenesis {
	return v.value
}

func (v *NullableEnvironmentCreateActionGenesis) Set(val *EnvironmentCreateActionGenesis) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentCreateActionGenesis) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentCreateActionGenesis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentCreateActionGenesis(val *EnvironmentCreateActionGenesis) *NullableEnvironmentCreateActionGenesis {
	return &NullableEnvironmentCreateActionGenesis{value: val, isSet: true}
}

func (v NullableEnvironmentCreateActionGenesis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentCreateActionGenesis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
