/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the EnvironmentVariableEdit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentVariableEdit{}

// EnvironmentVariableEdit An environment variable used during bunnyshell workflows.
type EnvironmentVariableEdit struct {
	Value NullableString `json:"value,omitempty"`
}

// NewEnvironmentVariableEdit instantiates a new EnvironmentVariableEdit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentVariableEdit() *EnvironmentVariableEdit {
	this := EnvironmentVariableEdit{}
	return &this
}

// NewEnvironmentVariableEditWithDefaults instantiates a new EnvironmentVariableEdit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentVariableEditWithDefaults() *EnvironmentVariableEdit {
	this := EnvironmentVariableEdit{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnvironmentVariableEdit) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvironmentVariableEdit) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *EnvironmentVariableEdit) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *EnvironmentVariableEdit) SetValue(v string) {
	o.Value.Set(&v)
}

// SetValueNil sets the value for Value to be an explicit nil
func (o *EnvironmentVariableEdit) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *EnvironmentVariableEdit) UnsetValue() {
	o.Value.Unset()
}

func (o EnvironmentVariableEdit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentVariableEdit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	return toSerialize, nil
}

type NullableEnvironmentVariableEdit struct {
	value *EnvironmentVariableEdit
	isSet bool
}

func (v NullableEnvironmentVariableEdit) Get() *EnvironmentVariableEdit {
	return v.value
}

func (v *NullableEnvironmentVariableEdit) Set(val *EnvironmentVariableEdit) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentVariableEdit) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentVariableEdit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentVariableEdit(val *EnvironmentVariableEdit) *NullableEnvironmentVariableEdit {
	return &NullableEnvironmentVariableEdit{value: val, isSet: true}
}

func (v NullableEnvironmentVariableEdit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentVariableEdit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
