/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// EmbeddedOrganizationCollection struct for EmbeddedOrganizationCollection
type EmbeddedOrganizationCollection struct {
	Item []OrganizationCollection `json:"item,omitempty"`
}

// NewEmbeddedOrganizationCollection instantiates a new EmbeddedOrganizationCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedOrganizationCollection() *EmbeddedOrganizationCollection {
	this := EmbeddedOrganizationCollection{}
	return &this
}

// NewEmbeddedOrganizationCollectionWithDefaults instantiates a new EmbeddedOrganizationCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedOrganizationCollectionWithDefaults() *EmbeddedOrganizationCollection {
	this := EmbeddedOrganizationCollection{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *EmbeddedOrganizationCollection) GetItem() []OrganizationCollection {
	if o == nil || o.Item == nil {
		var ret []OrganizationCollection
		return ret
	}
	return o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedOrganizationCollection) GetItemOk() ([]OrganizationCollection, bool) {
	if o == nil || o.Item == nil {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *EmbeddedOrganizationCollection) HasItem() bool {
	if o != nil && o.Item != nil {
		return true
	}

	return false
}

// SetItem gets a reference to the given []OrganizationCollection and assigns it to the Item field.
func (o *EmbeddedOrganizationCollection) SetItem(v []OrganizationCollection) {
	o.Item = v
}

func (o EmbeddedOrganizationCollection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Item != nil {
		toSerialize["item"] = o.Item
	}
	return json.Marshal(toSerialize)
}

type NullableEmbeddedOrganizationCollection struct {
	value *EmbeddedOrganizationCollection
	isSet bool
}

func (v NullableEmbeddedOrganizationCollection) Get() *EmbeddedOrganizationCollection {
	return v.value
}

func (v *NullableEmbeddedOrganizationCollection) Set(val *EmbeddedOrganizationCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedOrganizationCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedOrganizationCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedOrganizationCollection(val *EmbeddedOrganizationCollection) *NullableEmbeddedOrganizationCollection {
	return &NullableEmbeddedOrganizationCollection{value: val, isSet: true}
}

func (v NullableEmbeddedOrganizationCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedOrganizationCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
