/*
API Bunnyshell Environments

Interact with Bunnyshell Platform

API version: 1.1.0
Contact: osi+support@bunnyshell.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the EmbeddedEnvironItemCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbeddedEnvironItemCollection{}

// EmbeddedEnvironItemCollection struct for EmbeddedEnvironItemCollection
type EmbeddedEnvironItemCollection struct {
	Item []EnvironItemCollection `json:"item,omitempty"`
}

// NewEmbeddedEnvironItemCollection instantiates a new EmbeddedEnvironItemCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedEnvironItemCollection() *EmbeddedEnvironItemCollection {
	this := EmbeddedEnvironItemCollection{}
	return &this
}

// NewEmbeddedEnvironItemCollectionWithDefaults instantiates a new EmbeddedEnvironItemCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedEnvironItemCollectionWithDefaults() *EmbeddedEnvironItemCollection {
	this := EmbeddedEnvironItemCollection{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *EmbeddedEnvironItemCollection) GetItem() []EnvironItemCollection {
	if o == nil || IsNil(o.Item) {
		var ret []EnvironItemCollection
		return ret
	}
	return o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmbeddedEnvironItemCollection) GetItemOk() ([]EnvironItemCollection, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *EmbeddedEnvironItemCollection) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given []EnvironItemCollection and assigns it to the Item field.
func (o *EmbeddedEnvironItemCollection) SetItem(v []EnvironItemCollection) {
	o.Item = v
}

func (o EmbeddedEnvironItemCollection) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbeddedEnvironItemCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableEmbeddedEnvironItemCollection struct {
	value *EmbeddedEnvironItemCollection
	isSet bool
}

func (v NullableEmbeddedEnvironItemCollection) Get() *EmbeddedEnvironItemCollection {
	return v.value
}

func (v *NullableEmbeddedEnvironItemCollection) Set(val *EmbeddedEnvironItemCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedEnvironItemCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedEnvironItemCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedEnvironItemCollection(val *EmbeddedEnvironItemCollection) *NullableEmbeddedEnvironItemCollection {
	return &NullableEmbeddedEnvironItemCollection{value: val, isSet: true}
}

func (v NullableEmbeddedEnvironItemCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedEnvironItemCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
